trigger:
- none

pool:
  name: batch3-cicd-pool
  vmImage: ansiblecicd

steps:
- task: Bash@3
  displayName: "Ansible syntax check"
  inputs:
    targetType: 'inline'
    script: 'ansible-playbook -i hosts myplay.yaml --syntax-check'
    failOnStderr: true
- task: Bash@3
  displayName: "Ansible dry run "
  inputs:
    targetType: 'inline'
    script: 'ansible-playbook -i hosts myplay.yaml -C'
    failOnStderr: true