trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'remoteansiblelogin'
    playbookSourceRemoteMachine: 'ansibleMachine'
    playbookPathAnsibleMachineOnRemoteMachine: '$(System.DefaultWorkingDirectory)/ansiblecicd/myplay.yaml'
    inventoriesRemoteMachine: 'file'
    inventoryFileSourceRemoteMachine: 'ansibleMachine'
    inventoryFileAnsibleMachineOnRemoteMachine: '$(System.DefaultWorkingDirectory)/ansiblecicd/hosts'