trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'myplay.yaml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: 'hosts'
