trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansiblecicd/myplay.yaml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansiblecicd/hosts'
